### PR TITLE
Pull request for code review

### PR DESCRIPTION
**Pull request by AymenBida**
### Newsweek clone project

In this project we did :

- add content and style individual blocks
- use bootstrap classes for margins and padding and positioning everything
- use SASS to nest CSS code and use variables

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @ & @**

Great job with the project so far it looks amazing. this is by far the best first review i've ever seen. There are still some changes to be made:
 
---
### Requested 🔴 

- [x] please fix all of your linters issues.

- [x] if you are going to use container-xl on the body, then add p-0 to it to remove the additional padding.

- [x] this is a bootstrap project, so you have to use bootstrap classes everywhere possible.
you can still use regular CSS for the stuff that requires precision and colors.

- [x] the original page has 2 breakpoints 992px and 768px yours are at 1092px and 845px, please fix this issue.

- [x] the featured stories section is missing in the mobile view. please make sure to add it. 


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by AymenBida** [comment]
### Pull request for code review #2 

in this one we corrected : 

- linter errors
- paddings on the containers
- the features stories section is in the right place now
- the media rules are correct

**Comment by mimipeshy** [comment]
## STATUS : CHANGES REQUIRED 🔴 ♻️ 
Hey team @AymenBida and @FrederickMih 👋 👋 , you guys did soo well in this project, it looks like the original website 💯 
However before we can mark it as complete, check out the comments below:

- [x]  In the mobile view, the article order should be Top story, featured story, debate section,opinion section, more stories, and lastly my turn section.  In your clone, you have ordered it as Top story, featured story, my turn section, more stories, the debate section.  Please re-order them 😄 [link](https://www.newsweek.com/)

- [x] The Newsweek logo is missing on both the mobile view and tablet view. Kindly add it. [link](https://www.newsweek.com/)

- [x] On the README file, the setup instructions are vague to someone who is new to github 😄 , instead of saying `Clone the repository to your folder of choice using Git (or just download all the files)` you can say `git clone <repo_name>`, does the user need to cd into a folder? ` git cd <folder_name>` how does a user run your file? add that as well


✔️ Overall your project really looks awesome😄 

That's all. 😄 , kindy submit another review when you are done

Regards
Peris Ndanu
Feel free to reach out on slack if you have any questions

**Comment by AymenBida** [comment]
### Pull request for code review #3

In this one we did :

- correct the order of sections in the mobile version
- fixed the logo that wasn't showing
- edited the readme file making it more user friendly

**Review by layzrd — APPROVED** [review]
### Status: Approved 🙌 🎇
Hi @AymenBida and @FrederickMih, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR. Congratulations 🎊 👏, you did very well on this project. 👏👏👏  I appreciate your hard work on replicating newsweek.com.

Now, you can move ahead.

Please don't forget to merge to master. Good luck with the next projects!

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Pull request merged**
